### ISSUE TITLE
Exception on config on v1523a23

### ISSUE THREAD

**Issue by jwelter1971** [niemyjski/homeassistant-kohler#4]
```
2020-02-02 17:03:10 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 419, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 153, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/usr/src/homeassistant/homeassistant/helpers/temperature.py", line 27, in display_temp
    temperature = convert_temperature(temperature, temperature_unit, ha_unit)
  File "/usr/src/homeassistant/homeassistant/util/temperature.py", line 29, in convert
    raise ValueError(UNIT_NOT_RECOGNIZED_TEMPLATE.format(from_unit, TEMPERATURE))
ValueError: None is not a recognized temperature unit.

```

**Comment by niemyjski** [comment]
Thanks for reporting this
